### ISSUE TITLE
AssertionError: {'action': array([nan, nan, nan, nan, nan, nan], dtype=float32), 'reset': array(False)}

### ISSUE THREAD

**Issue by Liuxueyi** [chandar-lab/Recall2Imagine#2]
When I use the default config.yaml to run the experiments of Memory Maze and POPGym, the following error occurs:
`Process env:
Traceback (most recent call last):
  File "/conda/miniconda/envs/py38/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/conda/miniconda/envs/py38/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/code/recall2imagine/embodied/core/distr.py", line 199, in _wrapper
    fn(*args)
  File "/code/recall2imagine/embodied/run/parallel.py", line 172, in env
    obs = env.step(act)
  File "/code/recall2imagine/embodied/core/wrappers.py", line 376, in step
    obs = self.env.step(action)
  File "/code/recall2imagine/embodied/core/wrappers.py", line 160, in step
    obs = self.env.step(action)
  File "/code/recall2imagine/embodied/core/wrappers.py", line 115, in step
    assert action[self._key].min() == 0.0, action
AssertionError: {'action': array([nan, nan, nan, nan, nan, nan], dtype=float32), 'reset': array(False)}
`
It seems to be related to env reset. Could you give me some suggestions on why the error occurs and how to solve it? Looking forward to your reply.

**Comment by Lr-2002** [comment]
hi guys , I'm also reproducing the project, Let's make a telegram channel for immediate communication?

**Comment by Lr-2002** [comment]
https://t.me/+kFtu63HMopQ3Njg0

**Comment by Liuxueyi** [comment]
It related with the gpus used with policy_devices and train_devices.

**Comment by artemZholus** [comment]
Hi , @Liuxueyi 

did you resolve the issue? How? We observed this type of error in our experiments but it was extremely rare. 

I am hiding the link for the telegram chat as the best way to communicate with us is through isssues here.

**Comment by Liuxueyi** [comment]
From my point of view, the error occurs when the policy_devices is set to be [0] while the train_devices is set to be [0, 1]. When I make policy_devices and train_devices the same, the error is resolved. This issue may be related to jax.

**Comment by Liuxueyi** [comment]
By the way, could you provide me with the time consumption on each task? And what gpu devices do you use?

**Comment by artemZholus** [comment]
@Liuxueyi I will answer the questions above later. Just wanted to mention that you might benefit from the argument `--unlocked_sampling True`  in Memory Maze. However, we DO NOT guarantee exactly the same sample efficiency as reported in our paper when using that argument. It lets the model to sample experinces as fast as possible and train as fast as possible.  With that enabled, you should tune your number of workers to reach the training_ratio of `50` (shows up in wandb) which we had when doing unlocked sampling.

**Comment by artemZholus** [comment]
With this enabled you'll have the highest GPU utilization. For us 400M samples with this argument took 14 days on two A100 gpus. See the last page of the paper for more details.
