### ISSUE TITLE
POPGym performance issue. 

### ISSUE THREAD

**Issue by Lr-2002** [chandar-lab/Recall2Imagine#3]
Hi, @artemZholus I'm now reproducing your projec(popgym) in my PC.
The rep and dyn loss seems to be stable While the score is very different from your figure, Especially the steps after 40M
![image](https://github.com/chandar-lab/Recall2Imagine/assets/42893558/69071405-a802-40d6-9fee-6f1b0bf2b9e8)
After searching, I've find that the act_opt_loss is very bad ,You can see it as here.

![image](https://github.com/chandar-lab/Recall2Imagine/assets/42893558/f09ec530-5ac7-4173-94ad-de7b4ed99eb6)

I'm just using the code and config as your repo, using the command you provided.
Notice: The running was once interupt at 20M and i rerun it ,It resume to run from 20M to 120 M
Could you help me ?

**Comment by Lr-2002** [comment]
rep loss.
![image](https://github.com/chandar-lab/Recall2Imagine/assets/42893558/94e9bf10-af49-431b-a05f-d8c4f0fb39b8)

dyn loss
![image](https://github.com/chandar-lab/Recall2Imagine/assets/42893558/23e64f26-83e5-44e9-bbbb-19fdf8cfc29d)

**Comment by artemZholus** [comment]
Hi , @Lr-2002 , let me take a look.

**Comment by Lr-2002** [comment]
ok, do you need wandb access? or something else ?

**Comment by artemZholus** [comment]
Hi @Lr-2002 . After a quick investigation I found there was some mismatch is the configuration for popgym. The mismatch is only in the network sizes (to the best of my knowledge). Note that memory-maze configs are unaffected and they successfully reproduce the results from the paper (I reproduced them with this code just before the release).  I put the fixed config into PR #4 , please check it. I will run some additional reproduction experiments on my side to make sure things are fine.

**Comment by Lr-2002** [comment]
Well, have you tried to run with the config file ? It remains other bugs.

```bash
TypeError: add got incompatible shapes for broadcasting: (8, 1024), (8, 512).
```

**Comment by artemZholus** [comment]
Yes. You need to delete your previous contents of your logs directory as it contains a saved model with different tensor shapes. (or specify a different logging directory)

**Comment by Lr-2002** [comment]
ohhh，thanks.Let me check it

**Comment by artemZholus** [comment]
Closing this issue due to the lack of activity. Please reopen if you have any other issues.
